verbos

create table verbos(
	IDVerbo	INTEGER NOT NULL,
	Tipo byte not null, --Tipo de Verbo: 1:Regular; 2:Irregular
	Infinitive string(20) not null, --Tempo verbal Infinitive
	SimplePast string(20) not null, --Tempo verbal SimplePast
	Participle string(20) not null, --Tempo verbal Participle
	Meaning string(100) not null, -- Significado
	Pronunciation_Infinitive string(50) not null, --Escrita da pronúncia no tempo verbal Infinitive
	Pronunciation_SimplePast string(50) not null, --Escrita da pronúncia no tempo verbal SimplePast
	Pronunciation_Participle string(50) not null, --Escrita da pronúncia no tempo verbal Participle
	Inf_eq_Simple byte not null, --Infinive = Simple?
	Inf_eq_Part  byte not null, --Infinive = Participle?
	Simple_eq_Part  byte not null, --Simple = Participle?
	PRIMARY KEY("IDVerbo" AUTOINCREMENT)
);
	
create table usos (
	IDUso integer not null,
	IDVerbo integer not null, 
	Use_Infinitive string(200),
	Use_SimplePast string(200),
	Use_Participle string(200),
	PRIMARY KEY("IDUso" AUTOINCREMENT)
);	


select * from verbos
--where Inf_eq_Simple = 1 --Infinitive = Simple
--where Inf_eq_Part = 1 --Infinitive = Paticiple
--where Simple_eq_Part = 1 == Simple = Participle
where Inf_eq_Simple+Inf_eq_Part+Simple_eq_Part = 3 --All iguals


Gerar via Excel
=CONCATENAR("insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2";",'";A2;"','";B2;"','";C2;"','";D2;"',";E2;",";F2;",";G2;",'','','');")


insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to arise','arose','arisen','erguer, levantar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to awake','awoke','awoken','acordar, despertar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to be','was / were','been','ser, estar, ficar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bear','bore','borne','suportar, aguentar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to beat','beat','beaten','bater, espancar, superar, vibrar, palpitar',1,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to become','became','become','tornar-se',0,1,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to begin','began','begun','começar, iniciar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bend','bent','bent','curvar, entortar, franzir, dirigir, desistir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bet','bet','bet','apostar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bid','bade','bidden','oferecer, convidar, ordenar, desejar, leiloar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bind','bound','bound','atar, amarrar, obrigar',0,0,1,'','','');

insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bite','bit','bitten','morder, engolir a isca',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bleed','bled','bled','sangrar, perder sangue;',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to blow','blew','blown','soprar, assobiar, fazer soar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to break','broke','broken','quebrar, romper, violar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to breed','bred','bred','procriar, gerar, fazer criação, educar, ensinar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to bring','brought','brought','trazer, servir, causar, executar, induzir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to build','built','built','construir, edificar, fabricar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to burn','burnt','burnt','queimar, incendiar, carbonizar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to burst','burst','burst','arrebentar, explodir, brotar, exclamar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to buy','bought','bought','comprar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to cast','cast','cast','arremessar, jogar, derrubar, moldar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to catch','caught','caught','pegar, capturar, entender, adquirir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to choose','chose','chosen','escolher, selecionar, preferir',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to cling','clung','clung','pegar-se, unir-se, aderir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to clothe','clothed','clothed','vestir, cobrir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to come','came','come','vir, chegar',0,1,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to cost','cost','cost','custar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to creep','crept','crept','engatinhar, arrastar-se no chão, andar de rasto',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to crow','crew','crowed','cacarejar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to cut','cut','cut','cortar, partir, reduzir, recortar, castrar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to deal','dealt','dealt','dar, distribuir, repartir, dividir, espalhar, negociar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to dig','dug','dug','cavar, escavar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to do','did','done','fazer',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to draw','drew','drawn','desenhar, extrair, sair',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to drink','drank','drunk','beber',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to drive','drove','driven','dirigir, guiar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to dwell','dwelt','dwelt','residir, ficar por um tempo, enfatizar, insistir em',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to eat','ate','eaten','comer',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to fall','fell','fallen','cair, desaguar, abater-se, decrescer, diminuir',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to feed','fed','fed','alimentar, nutrir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to feel','felt','felt','sentir, notar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to fight','fought','fought','lutar, brigar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to find','found','found','achar, encontrar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to flee','fled','fled','fugir, escapar, evitar, correr',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to fling','flung','flung','lançar, arremessar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to fly','flew','flown','voar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to forbid','forbade','forbidden','proibir',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to forget','forgot','forgotten','esquecer(-se)',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to forgive','forgave','forgiven','perdoar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to forsake','forsook','forsaken','abandonar, desertar, largar; abrir mão de',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to freeze','froze','frozen','congelar, gelar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to get','got','got','obter, conseguir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to give','gave','given','dar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to go','went','gone','ir',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to grow','grew','grown','crescer, florescer, germinar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hang','hung','hung','pendurar, suspender',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to have','had','had','ter, possuir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hear','heard','heard','ouvir, escutar, ter notícias',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to heave','hove','hove','puxar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hew','hewed','hewn','reduzir, talhar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hide','hid','hidden','esconder(-se), ocultar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hit','hit','hit','bater, chocar-se',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hold','held','held','segurar, agarrar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to hurt','hurt','hurt','ferir(-se), machucar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to keep','kept','kept','manter, conservar, preservar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to kneel','knelt','knelt','ajoelhar-se',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to knit','knit','knit','tricotar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to know','knew','known','saber, conhecer',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to lay','laid','laid','pôr, colocar, derrubar, deitar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to lead','led','led','conduzir, liderar, dirigir, comandar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to leap','leapt','leapt','saltar, pular, transportar, cobrir (os animais)',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to learn','learnt','learnt','aprender, ficar sabendo',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to leave','left','left','partir, deixar, sair',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to lend','lent','lent','emprestar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to let','let','let','permitir, deixar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to lie','lay','lain','deitar, jazer',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to light','lit','lit','acender, iluminar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to lose','lost','lost','perder',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to make','made','made','fazer, criar, elaborar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to mean','meant','meant','significar, querer dizer',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to meet','met','met','encontrar(-se), reunir(-se)',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to partake','partook','partaken','participar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to pay','paid','paid','pagar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to put','put','put','pôr, colocar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to quit','quit','quit','desistir, abandonar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to read','read','read','ler, interpretar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to ride','rode','ridden','cavalgar, andar de bibicleta ou carro',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to ring','rang','rung','soar, tocar (campainha, telefone)',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to rise','rose','risen','erguer-se, levantar-se',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to run','ran','run','correr, apressar-se',0,1,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to saw','sawed','sawn','serrar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to say','said','said','dizer, afirmar, declarar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to see','saw','seen','ver, perceber',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to seek','sought','sought','procurar, pedir, almejar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sell','sold','sold','vender',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to send','sent','sent','enviar, mandar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to set','set','set','pôr, dispor, ajustar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sew','sewed','sewn','costurar, coser',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shake','shook','shaken','sacudir, agitar, apertar a mão (em cumprimento)',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shed','shed','shed','derramar, vazar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shine','shone','shone','brilhar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shoot','shot','shot','atirar, ferir com tiro',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to show','showed','shown','mostrar, apresentar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shred','shred','shred','cortar em pedaços, picar, retalhar, rasgar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shrink','shrank','shrunk','contrair, encolher, recuar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to shut','shut','shut','fechar, cerrar; tampar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sing','sang','sung','cantar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sink','sank','sunk','afundar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sit','sat','sat','sentar(-se)',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to slay','slew','slain','matar, assassinar, destruir, arruinar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sleep','slept','slept','dormir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to slide','slid','slid','escorregar, deslizar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sling','slung','slung','atirar, arremessar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to smell','smelt','smelt','cheirar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to smite','smote','smitten','bater, espancar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sow','sowed','sown','semear',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to speak','spoke','spoken','falar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spell','spelt','spelt','soletrar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spend','spent','spent','gastar (dinheiro), passar (tempo)',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spill','spilt','spilt','derramar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spin','spun','spun','girar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spit','spat','spit','cuspir',0,1,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spoil','spoilt','spoilt','estragar, destruir',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spread','spread','spread','espalhar, estender',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to spring','sprang','sprung','saltar, lançar-se, libertar-se',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to stand','stood','stood','ficar ou pôr-se de pé',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to steal','stole','stolen','roubar, furtar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to stick','stuck','stuck','cravar, fincar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sting','stung','stung','picar, ferroar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to stink','stank','stunk','feder; enojar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to strew','strewed','strewn','espalhar, polvilhar, aspergir',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to stride','strode','stridden','caminhar, cavalgar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to strike','struck','struck','bater, golpear',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to string','strung','strung','amarrar, pendurar, enfiar, esticar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to strive','strove','striven','aspirar, tentar, esforçar-se',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to swear','swore','sworn','jurar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sweat','sweat','sweat','suar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to sweep','swept','swept','varrer',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to swell','swelled','swollen','inchar (-se), crescer, encher (os pneus)',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to swim','swam','swum','nadar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to swing','swung','swung','balançar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to take','took','taken','tomar, pegar, levar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to teach','taught','taught','ensinar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to tear','tore','torn','chorar, lacrimejar; rasgar, rachar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to tell','told','told','dizer, contar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to think','thought','thought','pensar, achar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to thrive','throve','thriven','ter sucesso',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to throw','threw','thrown','lançar, atirar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to thrust','thrust','thrust','empurrar',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to tread','trod','trodden','pisar, andar, pôr os pés',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to understand','understood','understood','entender, compreender',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to wake','woke','woken','acordar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to wear','wore','worn','vestir, usar, trajar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to weave','wove','woven','tecer, trançar',0,0,0,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to weep','wept','wept','chorar',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to wet','wet','wet','molhar, umedecer',1,1,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to win','won','won','ganhar, vencer',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to wind','wound','wound','girar, enrolar-se',0,0,1,'','','');
insert into verbos (Tipo,Infinitive,SimplePast,Participle,Meaning,Inf_eq_Simple,Inf_eq_Part,Simple_eq_Part,Pronunciation_Infinitive,Pronunciation_SimplePast,Pronunciation_Participle) values (2,'to wring','wrung','wrung','torcer',0,0,1,'','','');
